[📦 NEW] -c|--config $config_yaml

diff --git a/hello-world b/hello-world
--- a/hello-world
+++ b/hello-world
@@ -6,7 +6,7 @@
 # Header
 ARGUMENTS="\
   [-a|--approval]              whether to ask user for approval
-  [-c|--config]                specify path to the configuration file
+  [-y|--yaml]                  specify path to the configuration file
   -n \$count                    print \$count times
   [\$string]                    something other than \"Hello, world!\" to print
 "
@@ -21,8 +21,8 @@ while (( ${#} > 0 )); do
   case "${1}" in
   # [-a|--approval]              whether to ask user for approval
   '-a'|'--approval') approval_required=true ;;
-  # [-c|--config]                specify path to the configuration file
-  '-c'|'--config') shift && config=${1} ;;
+  # [-y|--yaml]                specify path to the configuration file
+  '-y'|'--yaml') shift && yaml=${1} ;;
   # -n \$count                    print \$count times
   '-n') shift && count=${1} ;;
   *)
@@ -45,24 +45,23 @@ if ${approval_required} && ! confirm; then
   exit 0
 fi
 
-if [[ -n "${config+x}" ]]; then
+if [[ -n "${yaml+x}" ]]; then
   if command -v yq &> /dev/null; then
-    start-spinner 'Printing entries from config.yaml...'
+    start-spinner "Printing entries from ${yaml}..."
     for (( i = 0; i < count; ++i )); do
-      yq -r '.data | to_entries | map(select(.value != null) | "\(.key) \(.value)") | .[]' < "${config}"
+      yq -r '.data | to_entries | map(select(.value != null) | "\(.key) \(.value)") | .[]' < "${yaml}"
     done
     stop-spinner ${?}
   else
-    printf 'yq is required to read %s. Skipping...' "${config}" >&2
+    printf 'yq is required to read %s. Skipping...' "${yaml}" >&2
   fi
-  exit ${?}
+else
+  start-spinner 'Printing...'
+  for (( i = 0; i < count; ++i )); do
+    printf '%s\n' "${string}"
+  done
+  stop-spinner ${?}
 fi
-
-start-spinner 'Printing...'
-for (( i = 0; i < count; ++i )); do
-  printf '%s\n' "${string}"
-done
-stop-spinner ${?}
 
 disable-spinners
 stop-spinner
@@ -71,7 +70,6 @@ start-spinner 'Even order doesn''t count.'
 start-spinner 'Spinners are off.'
 enable-spinners
 
-. ./lib/yaml-to-env "${SCRIPT_PATH}/config.yaml"
-start-spinner 'Printing environment variables taken from YAML...'
-printf 'this: %s\n' "${this}"
-stop-spinner ${?}
+if [[ -n "${this+x}" ]]; then
+  printf 'this %s\n' "${this}"
+fi
diff --git a/lib/header b/lib/header
--- a/lib/header
+++ b/lib/header
@@ -21,20 +21,58 @@ ${ARGUMENTS}"
   printf \
 'Usage: %s {{options}} %s
 Options:
-  [-d|--debug]                 Enables debug mode, showing every executed statement.
+  [-c|--config $config_yaml]   Reads from a YAML configuration and converts all
+                               key-value pairs with literal values to
+                               environment variables.
+  [-d|--debug]                 Enables debug mode, showing every executed
+                               statement.
   [-h|--help]                  Prints usage (this text).%s' \
     "$(basename "${0}")" "${arguments}" "${ARGUMENTS}"
 }
+
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+LIB_PATH="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+
+# Colors
+RESET='\e[1m\e[0m'
+BLACK='\e[1m\e[30m'
+RED='\e[1m\e[31m'
+GREEN='\e[1m\e[32m'
+YELLOW='\e[1m\e[33m'
+BLUE='\e[1m\e[34m'
+PURPLE='\e[1m\e[35m'
+CYAN='\e[1m\e[36m'
+WHITE='\e[1m\e[37m'
 
 # Parse arguments.
 i=1
 while (( i <= ${#} )); do
   case "${!i}" in
-  # Debug mode
-  '-d'|'--debug') set -x; set -- ${*:1:$((i - 1))} ${*:$((i + 1))}; i=$((i - 1)) ;;
-  # Help: display usage
-  '-h'|'--help') print-usage; exit 0 ;;
-  esac; (( ++i ))
+  # [-c|--config $config_yaml]   Reads from a YAML configuration and converts all
+  #                              key-value pairs with literal values to
+  #                              environment variables.
+  '-c'|'--config')
+    ii=$((i + 1))
+    if (( ii > ${#} )); then
+      printf "${RED}ERROR: YAML configuration file not provided for -c|--config option${RESET}\\n" >&2
+      exit 1
+    fi
+    . "${LIB_PATH}/yaml-to-env" "${!ii}"
+    set -- ${*:1:$((i - 1))} ${*:$((i + 2))}; i=$((i - 2))
+    ;;
+  # [-d|--debug]                 Enables debug mode, showing every executed
+  #                              statement.
+  '-d'|'--debug')
+    set -x
+    set -- ${*:1:$((i - 1))} ${*:$((i + 1))}; i=$((i - 1))
+    ;;
+  # [-h|--help]                  Prints usage (this text).
+  '-h'|'--help')
+    print-usage
+    exit 0
+    ;;
+  esac;
+  i=$(( ++i ))
 done
 
 # Source guard
@@ -45,17 +83,17 @@ export _LIB_HEADER_SOURCED=true
 export -f print-usage
 
 # Get script path and append it to PATH so other scripts are callable.
-export SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
-export LIB_PATH="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+export LIB_PATH
+export SCRIPT_PATH
 export PATH="${PATH}:${SCRIPT_PATH}"
 
 # Colors
-export RESET='\e[1m\e[0m'
-export BLACK='\e[1m\e[30m'
-export RED='\e[1m\e[31m'
-export GREEN='\e[1m\e[32m'
-export YELLOW='\e[1m\e[33m'
-export BLUE='\e[1m\e[34m'
-export PURPLE='\e[1m\e[35m'
-export CYAN='\e[1m\e[36m'
-export WHITE='\e[1m\e[37m'
+export RESET
+export BLACK
+export RED
+export GREEN
+export YELLOW
+export BLUE
+export PURPLE
+export CYAN
+export WHITE
