renamed functions (minor change)

diff --git a/hello-world b/hello-world
--- a/hello-world
+++ b/hello-world
@@ -25,19 +25,19 @@ while (( ${#} > 0 )); do
   '-n') shift && count=${1} ;;
   *)
     # [\$string]                    something other than \"Hello, world!\" to print
-    [[ -z ${string} ]] && string="${1}" && shift && continue
+    [[ -z "${string+x}" ]] && string="${1}" && shift && continue
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
   esac; shift
 done
 
 mandatory count
 
-[[ -z ${string+x} ]] && string="Hello, world!"
+[[ -z "${string+x}" ]] && string="Hello, world!"
 
 #------------------------------------------------------------------------------#
 
-start_spinner "Printing..."
+start-spinner "Printing..."
 
 if ${confirm_required} && ! confirm; then
   exit 0
@@ -47,4 +47,4 @@ for (( i = 0; i < count; ++i )); do
   printf '%s\n' "${string}"
 done
 
-stop_spinner 0
+stop-spinner 0
diff --git a/install b/install
--- a/install
+++ b/install
@@ -23,14 +23,14 @@ confirm_required=false
 while (( ${#} > 0 )); do
   case "${1}" in
   # Unrecognized argument
-  *) printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+  *) printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
   esac; shift
 done
 
 #------------------------------------------------------------------------------#
 
-start_spinner "Installing..."
+start-spinner "Installing..."
 
 find "${SCRIPT_PATH}/lib" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | xargs -I{} bash -c "install -Dm644 '${SCRIPT_PATH}/lib/{}' '/usr/local/bin/lib/{}'"
 
-stop_spinner ${?}
+stop-spinner ${?}
